language: java
jdk:
  - openjdk7
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

# Skip the "installation" step:
# https://docs.travis-ci.com/user/customizing-the-build#Skipping-the-Installation-Step
install: true

script:
  # Builds the compiler and runs tests
  - mvn install --batch-mode
  # Checks for JavaDoc errors
  - mvn javadoc:javadoc

# Causes the build to run on a VM instead of in a container, to avoid OOM errors.
sudo: required

notifications:
  email: false
